connect/urls.py
from django.urls import path

from . import views

app_name = 'connect'

urlpatterns = [
    path('',views.index_view,name='index'),
    path('about/',views.about_view,name='about'),
    path('policy/',views.policy_view,name='policy'),

    path('sectors/',views.sector_list,name='sector-list'),
    path('sector/<int:id>/<int:type_>/',views.DisplayRequest.as_view(),name='display-request'),
    path('create-request/<int:id>/',views.CreateRequest.as_view(),name='create-request'),
    path('delete-request/<int:id>/',views.request_delete,name='delete-request'),
    path('detail-request/<int:id>/',views.detailed_request_view,name='detail-request'),
    path('addremove-sender/<int:id>/',views.add_or_remove_sender_view,name='addremove-sender'),
    path('list-senders/<int:id>',views.list_senders_in_request_view,name='list-senders'),
    path('final-add/<int:id>/<str:username>/',views.final_accept_view,name = 'final-addremove'),
    path('view-contact-sender/<int:id>/',views.view_contact_after_match_sender,name='view-contact-sender'),
    path('view-contact-receiver/<int:id>/<str:username>/',views.view_contact_after_match_receiver,name='view-contact-receiver'),
    path('deny-request/<int:id>/<str:username>/',views.deny_request_view,name='deny-request'),
    path('pending/',views.pending_list_view,name='pending'),
    path('accepted/',views.accepted_list_view,name='accepted'),
    path('completed/',views.completed_list_view,name='completed'),

    # API Endpoints
    path('api/list-genre/',views.genre_list_api,name='api-list-genre'),
]

digi_connect_src/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),

    # External
    path('accounts/', include('allauth.urls')),

    # Local
    path('',include('connect.urls',namespace='connect')),

]

templates/about.html
{% extends 'base.html' %}

{% block content %}

<h2 class="text-center mt-2">About Us</h2>
<hr>

<h4>Developed, Designed and Tested By:</h4>
<p>We are group of 3 friends pursuing undergraduate from Indian Institute of Information Technology , Design and Manufacturing , Chennai who are vastly interested in creating new ideas with interest.</p>
<ul>
    <li><a target="none" href="https://www.linkedin.com/in/divyamydv/">Divyam Yadav</a></li>
    <li><a target="none" href="https://www.linkedin.com/in/rohanshingre/">Rohan Shingre</a></li>
    <li><a target="none" href="https://www.linkedin.com/in/anonshubh/">Shubh Pathak</a></li>
</ul>
<p>Contact Us @ thesynergee@gmail.com</p>
<!-- <h2>Contributors: </h2> -->
<p>We encourage people to have a look at our repo on <a target="none" href="https://github.com/anonshubh/digi-connect">Github</a>, and provide us with feedback,suggestions and inputs. They are all very much apppreciated!!</p>


{% endblock %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

    <!-- Custom CSS  -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <!-- Font Awesome -->
    <script src="https://kit.fontawesome.com/a38aedba59.js" crossorigin="anonymous"></script>

    <!-- Fav-Icon  -->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'image/fav/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'image/fav/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'image/fav/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'image/fav/site.webmanifest' %}">

    <!-- Google Font  -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Lobster+Two:ital@1&display=swap" rel="stylesheet">

    <title>{% block title %}Let's Connect{% endblock %}</title>
    {% block head %} {% endblock %}
  </head>
  <body>
  
    <nav class="navbar navbar-expand-lg navbar-light sticky-top">
      <div class="container-fluid">
        <a class="navbar-brand dc-font" href="{% url 'connect:index' %}">DC</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'connect:sector-list' %}">Sectors</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                LookOut
              </a>
              <ul class="dropdown-menu nav-dropmenu" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item a-white" href="{% url 'connect:pending' %}">Pending</a></li>
                <li><a class="dropdown-item a-white" href="{% url 'connect:accepted' %}">Accepted</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item a-white" href="{% url 'connect:completed' %}">Completed</a></li>
              </ul>
            </li>
          </ul>
          <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
            <!-- <li class="nav-item">
              <a class="nav-link" aria-current="page" href="{% url 'connect:about' %}">About</a>
            </li> -->
            {% if request.user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'account_logout' %}">Log Out</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'account_login' %}">Log In</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'account_signup' %}">Sign Up</a>
            </li>
            {% endif %}
          </ul>
        
        </div>
      </div>
    </nav>

    <!-- Main Content  -->
    <div class="container">
      {% include 'messages_.html' %}
      {% block content %} {% endblock %}
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js" integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js" integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc" crossorigin="anonymous"></script>
    -->

    <!-- Custom Js -->
    <script src="{% static 'js/master.js' %}"></script>

    <!-- Page-Wise JS -->
    {% block script %} {% endblock %}

  </body>
</html>

templates/messages_.html
{% for message in messages %}
  <div class="alert alert-blur mt-1 {{ message.tags }} alert-dismissible fade show" role="alert">
    {{ message }}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
{% endfor %}

templates/policy.html
{% extends 'base.html' %}

{% block content %}
<h2 class="text-center mt-2">Terms & Policies</h2>
<a href="{% url 'connect:index' %}">Back To Home</a>
<hr>
<ol>
    <li>If found using Foul or Abusive Language you will be restricted for 5 days.</li>
    <li>If found harassing someone you will be permanently banned and judgement will be done under college rules for Anti Ragging.</li>
    <li>No Spamming Allowed. Spammers will be restricted for 3 days.</li>
    <li>Separate Division has been made in website for Freshers ( 1st year Btech) and other college students as per college's Anti Ragging Policy.</li>
    <li>Privacy Policy: Discloses the type of data you collect along with how it is stored and managed. This is a policy every arts organization should have.</li>
    <li>Terms of Service (TOS) Policy: Defines the rules by which an individual agrees to use a service. These are often called Terms of Use or Terms and Conditions. Although not always required by law, they are typically legally binding agreements that certainly help protect your organization and users.</li>
    <li>Disclaimer Policy: Indicates a site owner is not responsible for advice or information and limits liability. If your site includes content of a technical or legal nature, this is a must-have policy. Interestingly enough, this is one of the policies you’ll often find embedded into individual page alongside the respective content in addition to a general policy page or section.</li>
</ol>



{% endblock %}