connect/urls.py
from django.urls import path

from . import views

app_name = 'connect'

urlpatterns = [
    path('',views.index_view,name='index'),
    path('about/',views.about_view,name='about'),
    path('policy/',views.policy_view,name='policy'),

    path('sectors/',views.sector_list,name='sector-list'),
    path('sector/<int:id>/<int:type_>/',views.DisplayRequest.as_view(),name='display-request'),
    path('create-request/<int:id>/',views.CreateRequest.as_view(),name='create-request'),
    path('delete-request/<int:id>/',views.request_delete,name='delete-request'),
    path('detail-request/<int:id>/',views.detailed_request_view,name='detail-request'),
    path('addremove-sender/<int:id>/',views.add_or_remove_sender_view,name='addremove-sender'),
    path('list-senders/<int:id>',views.list_senders_in_request_view,name='list-senders'),
    path('final-add/<int:id>/<str:username>/',views.final_accept_view,name = 'final-addremove'),
    path('view-contact-sender/<int:id>/',views.view_contact_after_match_sender,name='view-contact-sender'),
    path('view-contact-receiver/<int:id>/<str:username>/',views.view_contact_after_match_receiver,name='view-contact-receiver'),
    path('deny-request/<int:id>/<str:username>/',views.deny_request_view,name='deny-request'),
    path('pending/',views.pending_list_view,name='pending'),
    path('accepted/',views.accepted_list_view,name='accepted'),
    path('completed/',views.completed_list_view,name='completed'),

    # API Endpoints
    path('api/list-genre/',views.genre_list_api,name='api-list-genre'),
]

digi_connect_src/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),

    # External
    path('accounts/', include('allauth.urls')),

    # Local
    path('',include('connect.urls',namespace='connect')),

]

connect/models.py
from django.db import models

from django.contrib.auth import get_user_model

User = get_user_model()


class GenreField(models.Model):
    """
    Different Genre For Each Sectors
    """
    genre_type = models.CharField(max_length=56,unique=True)


    def __str__(self):
        return (f'{self.genre_type}')[:15]


class SectorField(models.Model):
    """
    Relation For Each Sector, Example: Travel, Sports"
    """
    name = models.CharField(max_length=56,unique=True)
    image = models.URLField()
    genre = models.ManyToManyField(GenreField,related_name='sec')


    def __str__(self):
        return (f'{self.name}')[:15]



class Request(models.Model):
    """
    Relation For Request Posted By User
    """
    requester = models.ForeignKey(User,on_delete=models.CASCADE,blank=True,related_name='req')
    sector = models.ForeignKey(SectorField,on_delete=models.CASCADE,related_name='reqsec')
    genre = models.CharField(max_length=56,null=True,blank=True)
    subject = models.CharField(max_length=128)
    content = models.TextField()
    match_with_same_gender = models.BooleanField(default=False)
    deadline = models.DateTimeField()
    is_first_year_req = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    deleted = models.BooleanField(default=False)
    pending = models.BooleanField(default=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        subject = (self.subject)[:15]
        return f'By {self.requester}: {subject}'



class InitialMatchingRequest(models.Model):
    """
    Relation to Store Match after initial "Request" Send by User
    """
    request = models.ForeignKey(Request,on_delete=models.CASCADE,related_name='initialmatch')
    req_users = models.ManyToManyField(User,related_name='initialmatchuser')
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-updated']

    def __str__(self):
        return f'Initial Match of {self.request}'


class FinalMatchingRequest(models.Model):
    """
    Relation to Store Match after Final "Accept Back"
    """
    request = models.ForeignKey(Request,on_delete=models.CASCADE,related_name='finalmatch')
    final_req_users = models.ManyToManyField(User,related_name='finalmatchuser')
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-updated']

    def __str__(self):
        return f'Final Match of {self.request}'

connect/forms.py
from django import forms
from django.core.exceptions import ValidationError

from .models import Request


class RequestForm(forms.ModelForm):
    genre_list = forms.ChoiceField()
    class Meta:
        model = Request
        exclude = ('requester','pending','deleted','genre','is_first_year_req',)
        widgets = {
            'deadline': forms.DateTimeInput(attrs={'type':'datetime-local','class': 'form-control-sm'}),
            'content':forms.Textarea(attrs={'cols': 40, 'rows': 5}),
        }

connect/views.py
from django.shortcuts import render, get_object_or_404,redirect
from django.views.generic import View
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseNotAllowed, JsonResponse
from django.core.exceptions import ValidationError,PermissionDenied
from django.contrib import messages

from .models import GenreField,Request,SectorField,InitialMatchingRequest,FinalMatchingRequest
from .forms import RequestForm
import json, datetime, pytz


User = get_user_model()

# Index Page Of Entire Application
def index_view(request):
    sectors = SectorField.objects.all()
    data = {
        'sectors':sectors
    }
    return render(request,'connect/index.html',context=data)


# About Page Of Application
def about_view(request):
    return render(request,'about.html')

# Policy Page Of Application
def policy_view(request):
    return render(request,'policy.html')


# Returns the List of Available Sectors
def sector_list(request):
    sectors = SectorField.objects.all()
    data = {
        'sectors':sectors
    }
    return render(request,'connect/sector-list.html',context=data)


class DisplayRequest(LoginRequiredMixin,View):
    """
    Displays the Create Request Button with Recent Requests in Particular Sector
    """
    def get(self,request,id,type_,*args,**kwargs):
        sector = get_object_or_404(SectorField,pk=id)
        
        if request.user.info.year == 1:
            requests_ = Request.objects.filter(sector=sector,is_first_year_req = True,deleted=False,pending=True)
        else:
            requests_ = Request.objects.filter(sector=sector,is_first_year_req = False,deleted=False,pending=True)
        
        final_requests =  []
        for i in requests_:
            if(i.match_with_same_gender):
                if(request.user.info.gender == i.requester.info.gender):
                    final_requests.append(i)
            elif(type_ == 1):
                if(request.user.info.gender == i.requester.info.gender):
                    final_requests.append(i)
            else:
                final_requests.append(i)


        data = {
            'sector':sector,
            'requests':final_requests,
            'type_':type_,
        }
        return render(request,'connect/sector-detail.html',context=data)


class CreateRequest(LoginRequiredMixin,View):
    """
    Returns the Create-Request Form and After Submission, Saves the Data in db
    """
    def get(self,request,id,*args,**kwargs):
        sector = get_object_or_404(SectorField,pk=id) 
        form = RequestForm(initial={'sector':sector})
        data = {
            'form':form,
            'sector':sector,
        }
        return render(request,'connect/request-create.html',context=data)
    

    def post(self,request,id,*args,**kwargs):
        sector_id = int(request.POST.get('sector-id'))
        sector = get_object_or_404(SectorField,pk=sector_id)

        if(request.user.info.is_restricted):
            raise PermissionDenied()

        form = RequestForm(request.POST)
        if(form.is_valid()):
            pass     

        genre = request.POST.get('genre_list')
        subject = form.cleaned_data['subject']
        content = form.cleaned_data['content']
        deadline = form.cleaned_data['deadline']
        match_with_same_gender = request.POST.get("match_with_same_gender",None)

        # Custom Form Verification
        
        live = datetime.datetime.now(pytz.timezone('Asia/Kolkata'))
        if (live.date()==deadline.date()) and (live.time()>deadline.time()) or (live.date()>deadline.date()):
            messages.error(request,'Deadline Must Be Higher than Current Time!')
            return redirect('connect:create-request',id=sector_id)
    
        is_first_year_req = False
        if(request.user.info.year == 1):
            is_first_year_req = True

        if(match_with_same_gender is None):
            match_with_same_gender = False
        else:
            match_with_same_gender = True

        req_obj = Request.objects.create(
            requester = request.user,
            sector = sector,
            genre = genre,
            subject = subject,
            content = content,
            match_with_same_gender = match_with_same_gender,
            deadline = deadline,
            is_first_year_req = is_first_year_req
        )
        messages.success(request,"Your Request is Created Sucessfully!")
        return redirect('connect:display-request',id=sector_id,type_=0)


# Returns the Genere List for Particular Sector
@login_required
def genre_list_api(request):
    if request.method == 'POST':
        data_ =  json.loads(request.body)
        sector_id = data_.get('sector_id')

        sector = get_object_or_404(SectorField,pk=sector_id)

        data = {"sector-list":list()}
        genre_list = sector.genre.all()

        for i in genre_list:
            data['sector-list'].append(i.genre_type)
        return JsonResponse(data=data)
    return HttpResponseNotAllowed('GET')


# Deletes the Given Request
@login_required
def request_delete(request,id):
    req_obj = get_object_or_404(Request,pk=id)
    sector_id = req_obj.sector.id

    if(request.user != req_obj.requester):
        messages.error("Permission Denied!, You are Not Creater of Request.")
    else:
        req_obj.deleted = True
        req_obj.save()

    return redirect('connect:display-request',id=sector_id,type_=0)


# Displays the Detailed View of Given Request
@login_required
def detailed_request_view(request,id):
    req_obj = get_object_or_404(Request,pk=id)

    if req_obj.deleted:
        raise PermissionDenied()

    if (request.user.info.year != 1):
        if (req_obj.is_first_year_req):
            raise PermissionDenied()

    if (request.user.info.year == 1):
        if not (req_obj.is_first_year_req):
            raise PermissionDenied()
    
    if(req_obj.match_with_same_gender):
        if(request.user.info.gender != req_obj.requester.info.gender):
            raise PermissionDenied()
    
    already_sent = False
    initial_req_obj,created = InitialMatchingRequest.objects.get_or_create(request=req_obj)
    req_users = initial_req_obj.req_users.all()

    final_accepted = False
    final_req_obj,created1 = FinalMatchingRequest.objects.get_or_create(request=req_obj)
    final_req_users = final_req_obj.final_req_users.all()

    if(request.user in req_users):
        already_sent = True
    
    if(request.user in final_req_users):
        final_accepted = True

    context = {
        'req_object':req_obj,
        'already_sent':already_sent,
        'final_accepted':final_accepted
    }
    return render(request,'connect/request-detail.html',context=context)


# Adds New Requester to the Particular Request
@login_required
def add_or_remove_sender_view(request,id):
    req_obj = get_object_or_404(Request,pk=id)
    deadline = req_obj.deadline

    if req_obj.deleted:
        raise PermissionDenied()
    
    if (request.user == req_obj.requester):
        raise PermissionDenied()

    if (request.user.info.year != 1):
        if (req_obj.is_first_year_req):
            raise PermissionDenied()

    if (request.user.info.year == 1):
        if not (req_obj.is_first_year_req):
            raise PermissionDenied()
    
    if(req_obj.match_with_same_gender):
        if(request.user.info.gender != req_obj.requester.info.gender):
            raise PermissionDenied()

    live = datetime.datetime.now(pytz.timezone('UTC'))

    if (live.date()==deadline.date()) and (live.time()>deadline.time()) or (live.date()>deadline.date()):
        messages.error(request,'Deadline Exceeded!')
        req_obj.pending = False
        req_obj.save()
        return redirect('connect:detail-request',id=req_obj.id)
    
    initial_req_obj,created = InitialMatchingRequest.objects.get_or_create(request=req_obj)
    req_users = initial_req_obj.req_users.all()

    if(request.user in req_users):
        initial_req_obj.req_users.remove(request.user)
        messages.info(request,"Request Cancelled!")
    else:
        initial_req_obj.req_users.add(request.user)
        messages.success(request,"Request Sent Sucessfully!")
    
    return redirect('connect:detail-request',id=req_obj.id)
    

# Displays the List of Users Sent the Request for Particular Request
@login_required
def list_senders_in_request_view(request,id):
    req_obj = get_object_or_404(Request,pk=id)

    deadline = req_obj.deadline

    if req_obj.deleted:
        raise PermissionDenied()
    
    if (request.user.info.year != 1):
        if (req_obj.is_first_year_req):
            raise PermissionDenied()
    
    if (request.user != req_obj.requester):
        raise PermissionDenied()

    if (request.user.info.year == 1):
        if not (req_obj.is_first_year_req):
            raise PermissionDenied()
    
    if(req_obj.match_with_same_gender):
        if(request.user.info.gender != req_obj.requester.info.gender):
            raise PermissionDenied()

    live = datetime.datetime.now(pytz.timezone('UTC'))  
    if (live.date()==deadline.date()) and (live.time()>deadline.time()) or (live.date()>deadline.date()):
        messages.error(request,'Deadline Exceeded!')
        req_obj.pending = False
        req_obj.save()
        return redirect('connect:detail-request',id=req_obj.id)
    
    initial_req_obj,created = InitialMatchingRequest.objects.get_or_create(request=req_obj)
    req_users = initial_req_obj.req_users.all()

    final_req_obj,created1 = FinalMatchingRequest.objects.get_or_create(request=req_obj)
    final_req_users = final_req_obj.final_req_users.all()

    accepted_back = {}

    for i in req_users:
        if(i in final_req_users):
            accepted_back[i] = 1
        else:
            accepted_back[i] = 0

    context = {
        'req_obj':req_obj,
        'req_users':req_users,
        'accepted_back':accepted_back

connect/templates/connect/contact-sharing.html
{% extends 'base.html' %}

{% block content %}
<h3 class="text-center mt-2">Contact Share After Match :)</h3>
<hr>
<div class="row">
    <div class="col-lg-6 col-sm-12 my-2">
        <div class="card glass-container">
            <div class="card-body">
             <p class="lead text-center fw-bolder card-blackcolor">Your Details:</p> 
             <p class="card-blackcolor">Name: {{requesting.first_name}} {{requesting.last_name}}</p>
             <p class="card-blackcolor">UserHandle: {{requesting.username}}</p>
             <p class="card-blackcolor">Email: {{requesting.email}}</p>
             <p class="card-blackcolor">Phone: {{requesting.info.phone}}</p>
             <p class="card-blackcolor">Department: {{requesting.info.department}}</p>
             <p class="card-blackcolor">Year: {{requesting.info.year}}</p>
            </div>
          </div>
    </div>
    <div class="col-lg-6 col-sm-12 my-2">
        <div class="card glass-container">
            <div class="card-body">
            <p class="lead text-center fw-bolder card-blackcolor">Associate Details:</p> 
            <p class="card-blackcolor">Name: {{requester.first_name}} {{requester.last_name}}</p>
            <p class="card-blackcolor">UserHandle: {{requester.username}}</p>
            <p class="card-blackcolor">Email: {{requester.email}}</p>
            <p class="card-blackcolor">Phone: {{requester.info.phone}}</p>
            <p class="card-blackcolor">Department: {{requester.info.department}}</p>
            <p class="card-blackcolor">Year: {{requester.info.year}}</p>
            </div>
          </div>
    </div>
</div>

{% endblock %}

connect/templates/connect/delete-modal_.html
<!-- Modal -->
<div class="modal fade" id="deleteReqModal" tabindex="-1" aria-labelledby="deleteReqModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 style="color: black;" class="modal-title" id="deleteReqModalLabel">Confirmation!</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div style="color: black;" class="modal-body">
          Are You Sure Want to Delete?
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <a class="btn btn-danger" href="{% url 'connect:delete-request' req.id %}">Delete</a>
        </div>
      </div>
    </div>
  </div>
  

connect/templates/connect/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div id="intro">
        <div class="info-site">
            <h2 class="text-center mt-3">Digiconnect - Connecting People</h2>
            <p style="text-align: justify;">Even your friend is a stranger who you recognized.
                We help you identify strangers in the best possible setting at DigiConnect because we believe there is a better way to bring people together.
With a splash of randomness, our website will assist you in finding the ideal companion for travel, adventure, sports, gaming, and much more.
The main goal of this website is to bring individuals together based on their everyday lives.</p>
        </div>
        <br>
        <div class="text-center">
            <a class="btn btn-primary" href="#top-sectors">Explore Top Sectors</a>
            <a class="btn btn-primary mx-1 my-1" href="{% url 'connect:create-request' 1 %}">Create New Request +</a>
        </div>
        <div class="text-center mt-4">
            {% if not request.user.is_authenticated %}
                <a class="btn btn-warning mx-1" href="{% url 'account_login' %}">Log In</a>
                <a class="btn btn-warning mx-1" href="{% url 'account_signup' %}">Sign Up</a>
            {% endif %}
        </div>
</div>

<div id="top-sectors">
    <h2 class="text-center mt-2">Explore Top Sectors</h2>
    <div class="row mt-5">
        {% for sector in sectors %}
        <div class="col-lg-4 col-md-6 col-sm-12 mt-2">
            <div class="card glass-container" >
                <img src="{{sector.image}}" class="card-img-top" alt="...">
                <div class="card-body text-center">
                    <a href="{% url 'connect:display-request' sector.id 0 %}" class="btn btn-primary">Explore {{sector.name}}</a>
                </div>
            </div>
        </div>
        {% empty %}
        <p class="lead">No Sectors Available :(</p>
        {% endfor %}
    </div>
    <hr>
    <!-- Footer -->
    <div class="text-center">
        <p>Made with "Code" by <span class="footer-line-1"> <a class="team-s" target="_blank" href="{% url 'connect:about' %}">Team Synergee</a> </spam> | <a class="team-s" target="_blank" href="{% url 'connect:policy' %}">Our Policies</a></p>
        <p style="font-size: large;" class="footer-line-2 lead me-2">Write Us at <em>thesynergee@gmail.com</em> |</p> 
        <a target="_blank" class="linkedin-link mx-2" href="https://twitter.com/TSynergee"><i class="fab fa-twitter fa-2x"></i></a> <a target="_blank" class="instagram-link mx-2" href="https://www.instagram.com/thesynergee/"><i class="fab fa-instagram fa-2x"></i></a> <a target="_blank" class="linkedin-link mx-2" href="https://www.facebook.com/synergee.portal"><i class="fab fa-facebook-square fa-2x"></i></a>
      </div> 
</div>


{% endblock %}

connect/templates/connect/request-create.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}


{% block content %}
<h2>Create New Request For <span id='sector-name-heading'>{{sector.name}}</span></h2>
<hr>
<div class="row">
    <div class="col-lg-7 col-md-10 col-sm-12">
        <form action="{% url 'connect:create-request' sector.id %}" method="post">
            {% csrf_token %}
            {{form|crispy}}
            <input type="hidden" id="sector_id_hidden" name="sector-id" value={{sector.id}}>
            <input class="btn btn-primary mt-2" type="submit" value="Let's Create :)">
        </form>
    </div>
</div>


{% block script %} <script src="{% static 'js/create-request.js' %}"></script> {% endblock %}
{% endblock %}

connect/templates/connect/request-detail.html
{% extends 'base.html' %}

{% block content %}
<h3 class="text-center mt-3 mb-4">Live Request</h3>
<div class="row">
    <div class="col-lg-12 col-sm-6">
        <div class="glass-container card">
            <div class="card-body">
                <h5 class="card-title card-blackcolor text-center">{{req_object.subject}}</h5>
                <h6 class="card-subtitle mb-2 text-muted deadline-space mt-1">Deadline: {{req_object.deadline | date:'d-m-Y H:i'}}</h6>
                <hr>
                <p class="card-text card-blackcolor">{{req_object.content}}</p>
                {% if request.user != req_object.requester %}
                    {% if final_accepted %}
                        <a class="btn btn-success btn-sm ms-2 my-2" href="{% url 'connect:view-contact-sender' req_object.id %}">User Details</a>
                    {% else %}
                        {% if already_sent %}
                            <a href="{% url 'connect:addremove-sender' req_object.id %}" class="btn btn-warning btn-sm">Cancel!</a>
                        {% else %}
                            <a href="{% url 'connect:addremove-sender' req_object.id %}" class="btn btn-success btn-sm">Request :)</a>
                        {% endif %}
                    {% endif %}
                {% endif %}
                {% if request.user == req_object.requester %}
                    <a href="{% url 'connect:list-senders' req_object.id %}" class="card-link">Received Requests</a>
                {% endif %}
            </div>
        </div>
    </div>
</div>

{% endblock %}

connect/templates/connect/request-status.html
{% extends 'base.html' %}

{% block content %}
<h3 class="text-center mt-2">{{status}} Requests</h3>
<hr>
<div class="row">
    {% for req_object in object_list %}
    <div class="col-12 my-2">
        <div class="card glass-container">
            <div class="card-body">
                <h5 class="card-title card-blackcolor">{{req_object.subject}}</h5>
                <h6 class="card-subtitle mb-2 text-muted deadline-space mt-1">Deadline: {{req_object.deadline | date:'d-m-Y H:i'}}</h6>
                <p class="card-text card-blackcolor">{{req_object.content}}</p>
                <a class="btn btn-primary btn-sm" href="{% url 'connect:detail-request' req_object.id %}">View Details</a>
            </div>
        </div>
    </div>
    {% empty %}
    <p class="lead text-center">No {{status}} Requests</p>
    {% endfor %}
</div>

{% endblock %}

connect/templates/connect/requesting-list.html
{% extends 'base.html' %}
{% load custom_filters %}

{% block content %}
<h2 class="text-center">List of People Sent Request</h2>
<hr>
<p class="lead text-center">Subject: {{req_obj.subject}}</p>
    {% for user in req_users %}
        <div class="card glass-container my-2">
            <div class="row">
                <div class="col-lg-10 col-sm-12">
                    <div class="card-body">
                        <p style="color: black;" >Name: {{user.first_name}} {{user.last_name}}</p>
                        <p style="color: black;" >Handle: {{user.username}}</p> 
                    </div>
                </div>
                {% if accepted_back|get_item:user %}
                    <div class="col-lg-2 col-sm-12 ">
                        <a class="btn btn-primary btn-sm ms-2 my-3" href="{% url 'connect:view-contact-receiver' req_obj.id user.username %}">User Details</a>
                    </div>
                {% else %}
                    <div class="col-lg-2 col-sm-12 ">
                        <a class="btn btn-success btn-sm ms-2 my-2" href="{% url 'connect:final-addremove' req_obj.id user.username %}">Accept Back :)</a>
                        <a class="btn btn-danger btn-sm ms-2 my-2" href="{% url 'connect:deny-request' req_obj.id user.username %}">Deny :(</a>
                    </div>
                {% endif %}
            </div>
        
        </div>
    {% empty %}
        <p>No Request From Any User :(</p>
    {% endfor %}

{% endblock %}

connect/templates/connect/sector-detail.html
{% extends 'base.html' %}

{% block content %}

<h3 class="text-center">{{sector.name}}</h3>

<div class="row">
    <div class="col-lg-10 col-sm-12">
        <a class="btn btn-primary" href="{% url 'connect:create-request' sector.id %}">Create Request +</a>
    </div>
    <div class="col-lg-2 col-sm-12 mt-2">
        {% if type_ == 0 %}
            <a class="btn btn-secondary btn-sm" href="{% url 'connect:display-request' sector.id 1 %}">Show Results with "Same Gender"</a>
        {% else %}
            <a class="btn btn-secondary btn-sm" href="{% url 'connect:display-request' sector.id 0 %}">Show Original Results</a>
        {% endif %}
    </div>
</div>
<hr>
<div>
    <p class="lead">Recent Requests</p>
    {% for req in requests %}
        <div class="card glass-container my-2">
            <div class="card-body">
                <h6 class="card-subtitle card-greycolor mb-2">Deadline: {{req.deadline | date:'d-m-Y H:i'}}</h6>
                <p class="card-text card-blackcolor lead">{{req.subject}}</p>
                {% if request.user == req.requester %}
                    <button type="button" class="btn btn-danger btn-sm me-2" data-bs-toggle="modal" data-bs-target="#deleteReqModal">Delete</button>
                {% include 'connect/delete-modal_.html' %}
                {% endif %}           
                <a class="btn btn-primary btn-sm" href="{% url 'connect:detail-request' req.id %}">View Details</a>        
            </div>
        </div>
    {% empty %}
        <p>No Recent Requests :(</p>
    {% endfor %}
</div>


{% endblock %}

connect/templates/connect/sector-list.html
{% extends 'base.html' %}

{% block content %}
<h2 class="text-center mt-2">All Sectors</h2>
<a href="{% url 'connect:index' %}">Back To Home</a>
<hr>
<div class="row">
    {% for sector in sectors %}
    <div class="col-lg-4 col-md-6 col-sm-12 mt-2">
        <div class="card" style="width: 18rem;">
            <img class="card-img-top" src="{{sector.image}}" style="width: 100%;" alt="Image">
            <div class="card-img-overlay text-center">
                <a class="fw-bold" style="text-decoration: none;" href="{% url 'connect:display-request' sector.id 0 %}" >Explore {{sector.name}}</a>
            </div>
          </div>
    </div>
    {% empty %}
    <p class="lead text-center">No Sectors Available :(</p>
    {% endfor %}
</div>



{% endblock %}